#!/usr/bin/env python3
"""
Normalize Portuguese accents in site/content-translations.js.

Scans every JS string value (the right-hand side of each colon),
applies a known accent-correction dictionary, and writes the fixed file.
Only touches the pt-br translation values, never the English keys.
"""

import re
import sys

# ---- Accent correction dictionary ----
# Maps unaccented Portuguese word -> correctly accented Portuguese word
# Generated by auditing every unique word in the pt-br values
FIXES = {
    # Phase names
    "Configuracao": "Configuração",
    "Matematica": "Matemática",
    "Nucleo": "Núcleo",
    "Visao": "Visão",
    "Avancado": "Avançado",
    "Reforco": "Reforço",
    "Etica": "Ética",
    "Seguranca": "Segurança",
    "Producao": "Produção",
    "Autonomos": "Autônomos",

    # Frequent suffixes (also covered individually, but catch-all)
    "acao": "ação",
    "Acao": "Ação",
    "coes": "ções",
    "oes": "ões",
    "Oes": "ões",
    "cao": "ção",

    # Phase 0 - Setup
    "Colaboracao": "Colaboração",
    "Depuracao": "Depuração",

    # Phase 1 - Math
    "Intuicao": "Intuição",
    "Algebra": "Álgebra",
    "Transformacoes": "Transformações",
    "Calculo": "Cálculo",
    "Derivadas": "Derivadas",
    "Diferenciacao": "Diferenciação",
    "Automatica": "Automática",
    "Distribuicoes": "Distribuições",
    "Otimizacao": "Otimização",
    "Familia": "Família",
    "Informacao": "Informação",
    "Divergencia": "Divergência",
    "Reducao": "Redução",
    "Decomposicao": "Decomposição",
    "Numerica": "Numérica",
    "Distancias": "Distâncias",
    "Estatistica": "Estatística",
    "Metodos": "Métodos",
    "Convexa": "Convexa",
    "Numeros": "Números",
    "Complexos": "Complexos",
    "Estocasticos": "Estocásticos",

    # Phase 2 - ML
    "Regressao": "Regressão",
    "Logistica": "Logística",
    "Classificacao": "Classificação",
    "Arvores": "Árvores",
    "Decisao": "Decisão",
    "Nao": "Não",
    "Selecao": "Seleção",
    "Avaliacao": "Avaliação",
    "Vies": "Viés",
    "Variancia": "Variância",
    "Hiperparametros": "Hiperparâmetros",
    "Series": "Séries",
    "Deteccao": "Detecção",

    # Phase 3 - Deep Learning
    "Comecou": "Começou",
    "Funcoes": "Funções",
    "Ativacao": "Ativação",
    "Regularizacao": "Regularização",
    "Inicializacao": "Inicialização",
    "Proprio": "Próprio",
    "Introducao": "Introdução",

    # Phase 4 - CV
    "Convolucoes": "Convoluções",
    "Segmentacao": "Segmentação",
    "Semantica": "Semântica",
    "Geracao": "Geração",
    "Difusao": "Difusão",
    "Compreensao": "Compreensão",
    "Vocabulario": "Vocabulário",
    "Recuperacao": "Recuperação",
    "Estimativa": "Estimativa",
    "Memoria": "Memória",
    "Profundidade": "Profundidade",

    # Phase 5 - NLP
    "Tokenizacao": "Tokenização",
    "Analise": "Análise",
    "Etiquetacao": "Etiquetação",
    "Sintatico": "Sintático",
    "Mecanismo": "Mecanismo",
    "Atencao": "Atenção",
    "Traducao": "Tradução",
    "Modelagem": "Modelagem",
    "Topicos": "Tópicos",
    "Saidas": "Saídas",
    "Decodificacao": "Decodificação",
    "Constrangida": "Constrangida",
    "Inferencia": "Inferência",
    "Estrategias": "Estratégias",
    "Resolucao": "Resolução",
    "Coreferencia": "Coreferência",
    "Vinculacao": "Vinculação",
    "Desambiguacao": "Desambiguação",
    "Extracao": "Extração",
    "Relacoes": "Relações",
    "Construcao": "Construção",
    "Dialogo": "Diálogo",
    "Representacao": "Representação",

    # Phase 6 - Audio
    "Caracteristicas": "Características",
    "Espectrogramas": "Espectrogramas",
    "Conversao": "Conversão",
    "Clonagem": "Clonagem",
    "Atividade": "Atividade",

    # Phase 7 - Transformers
    "Aprofundamento": "Aprofundamento",

    # Phase 8 - Gen AI
    "Historia": "História",
    "Edicao": "Edição",

    # Phase 10 - LLMs
    "Paralelismo": "Paralelismo",
    "Pesagem": "Pesagem",
    "Diminuicao": "Diminuição",
    "Sobrescrita": "Sobrescrita",

    # Phase 11 - LLM Eng
    "Contexto": "Contexto",
    "Avaliacoes": "Avaliações",
    "Observabilidade": "Observabilidade",

    # Phase 13 - Tools
    "Fundamentos": "Fundamentos",

    # Phase 14 - Agents
    "Bancada": "Bancada",
    "Reutilizavel": "Reutilizável",
    "Observacao": "Observação",
    "Otel": "Otel",
    "Metricas": "Métricas",
    "Pre-Treinados": "Pré-Treinados",
    "Acumulacao": "Acumulação",
    "Executador": "Executador",
    "Avaliador": "Avaliador",
    "Hipoteses": "Hipóteses",
    "Gerador": "Gerador",
    "Agendador": "Agendador",
    "Iteracoes": "Iterações",
    "Literatura": "Literatura",
    "Escritor": "Escritor",
    "Papers": "Papers",
    "Critica": "Crítica",
    "Montagem": "Montagem",
    "Carregando": "Carregando",
    "Salvamento": "Salvamento",
    "Retomada": "Retomada",
    "Checkpoint": "Checkpoint",
    "Janela": "Janela",
    "Deslizante": "Deslizante",
    "Cabecalho": "Cabeçalho",
    "Rodape": "Rodapé",
    "Pre-Treinamento": "Pré-Treinamento",
    "Distribuido": "Distribuído",
    "Observabilidade": "Observabilidade",
    "Disponibilidade": "Disponibilidade",
    "Avaliacoes": "Avaliações",

    # Phase 15 - Autonomous
    "Raciocinio": "Raciocínio",
    "Auto-Didata": "Autodidata",
    "Evolucionarios": "Evolucionários",
    "Auto-Melhoria": "Automelhoria",
    "Recursiva": "Recursiva",
    "Limitada": "Limitada",
    "Panorama": "Panorama",
    "Permissao": "Permissão",
    "Automatico": "Automático",
    "Navegador": "Navegador",
    "Duracao": "Duração",
    "Orcamentos": "Orçamentos",
    "Acao": "Ação",
    "Iteracao": "Iteração",
    "Governadores": "Governadores",
    "Custo": "Custo",
    "Propor": "Propor",
    "Depois": "Depois",
    "Confirmar": "Confirmar",
    "Politica": "Política",
    "Escalonamento": "Escalonamento",
    "Responsavel": "Responsável",
    "Preparacao": "Preparação",
    "Framework": "Framework",
    "Horizontes": "Horizontes",
    "Externa": "Externa",
    "Risco": "Risco",
    "Escala": "Escala",
    "Societal": "Societal",

    # Phase 16 - Multi-agent
    "Primitivo": "Primitivo",
    "Arquitetura": "Arquitetura",
    "Hierarquica": "Hierárquica",
    "Sociedade": "Sociedade",
    "Mente": "Mente",
    "Debate": "Debate",
    "Especializacao": "Especialização",
    "Papel": "Papel",
    "Enxame": "Enxame",
    "Paralelo": "Paralelo",
    "Orador": "Orador",
    "Orquestracao": "Orquestração",
    "Stateless": "Stateless",
    "Memoria Compartilhada": "Memória Compartilhada",
    "Padroes": "Padrões",
    "Blackboard": "Blackboard",
    "Consenso": "Consenso",
    "Tolerancia": "Tolerância",
    "Falhas": "Falhas",
    "Bizantinas": "Bizantinas",
    "Votacao": "Votação",
    "Auto-Consistencia": "Autoconsistência",
    "Topologia": "Topologia",
    "Negociacao": "Negociação",
    "Barganha": "Barganha",
    "Generativos": "Generativos",
    "Simulacao": "Simulação",
    "Emergente": "Emergente",
    "Teoria": "Teoria",
    "Mente": "Mente",
    "Coordenacao": "Coordenação",
    "Emergente": "Emergente",
    "Otimizacao": "Otimização",
    "PSO": "PSO",
    "ACO": "ACO",
    "Economias": "Economias",
    "Incentivos": "Incentivos",
    "Token": "Token",
    "Reputacao": "Reputação",
    "Escalonamento": "Escalonamento",
    "Filas": "Filas",
    "Checkpoints": "Checkpoints",
    "Durabilidade": "Durabilidade",
    "Modos": "Modos",
    "Falha": "Falha",
    "Monocultura": "Monocultura",
    "Estudos": "Estudos",
    "Caso": "Caso",
    "Estado": "Estado",
    "Arte": "Arte",
    "Benchmarks": "Benchmarks",

    # Phase 17 - Infrastructure
    "Plataformas": "Plataformas",
    "Gerenciadas": "Gerenciadas",
    "Bedrock": "Bedrock",
    "Azure": "Azure",
    "Vertex AI": "Vertex AI",
    "Economia": "Economia",
    "Inferencia": "Inferência",
    "Fireworks": "Fireworks",
    "Together": "Together",
    "Baseten": "Baseten",
    "Modal": "Modal",
    "Autoscaling": "Autoscaling",
    "Kubernetes": "Kubernetes",
    "Karpenter": "Karpenter",
    "KAI Scheduler": "KAI Scheduler",
    "Internals": "Internals",
    "PagedAttention": "PagedAttention",
    "Continuous Batching": "Continuous Batching",
    "Chunked Prefill": "Chunked Prefill",
    "Decodificacao": "Decodificação",
    "Especulativa": "Especulativa",
    "EAGLE-3": "EAGLE-3",
    "RadixAttention": "RadixAttention",
    "Cargas": "Cargas",
    "Trabalho": "Trabalho",
    "Prefix-Heavy": "Prefix-Heavy",
    "Blackwell": "Blackwell",
    "FP8": "FP8",
    "NVFP4": "NVFP4",
    "Metricas": "Métricas",
    "TTFT": "TTFT",
    "TPOT": "TPOT",
    "ITL": "ITL",
    "Goodput": "Goodput",
    "P99": "P99",
    "Quantizacao": "Quantização",
    "AWQ": "AWQ",
    "GPTQ": "GPTQ",
    "GGUF": "GGUF",
    "Mitigacao": "Mitigação",
    "Cold Start": "Cold Start",
    "Serverless": "Serverless",
    "Servico": "Serviço",
    "Multi-Regiao": "Multi-Região",
    "Localidade": "Localidade",
    "Cache": "Cache",
    "Edge": "Edge",
    "ANE": "ANE",
    "Hexagon": "Hexagon",
    "WebGPU": "WebGPU",
    "Jetson": "Jetson",
    "Observabilidade": "Observabilidade",
    "Prompt Caching": "Prompt Caching",
    "Semantic Caching": "Semantic Caching",
    "Batch APIs": "Batch APIs",
    "Desconto": "Desconto",
    "Padrao": "Padrão",
    "Industria": "Indústria",
    "Roteamento": "Roteamento",
    "Modelos": "Modelos",
    "Primitiva": "Primitiva",
    "Reducao": "Redução",
    "Prefill/Decode": "Prefill/Decode",
    "Desagregado": "Desagregado",
    "NVIDIA Dynamo": "NVIDIA Dynamo",
    "llm-d": "llm-d",
    "LMCache KV Offloading": "LMCache KV Offloading",
    "Gateways": "Gateways",
    "LiteLLM": "LiteLLM",
    "Portkey": "Portkey",
    "Kong": "Kong",
    "Bifrost": "Bifrost",
    "Deploy": "Deploy",
    "Sombra": "Sombra",
    "Canary": "Canary",
    "Progressivo": "Progressivo",
    "Teste A/B": "Teste A/B",
    "Funcionalidades": "Funcionalidades",
    "GrowthBook": "GrowthBook",
    "Statsig": "Statsig",
    "Load Testing": "Load Testing",
    "k6": "k6",
    "LLMPerf": "LLMPerf",
    "GenAI-Perf": "GenAI-Perf",
    "Resposta": "Resposta",
    "Incidentes": "Incidentes",
    "Chaos Engineering": "Chaos Engineering",
    "Seguranca": "Segurança",
    "Secrets": "Secrets",
    "Limpeza": "Limpeza",
    "PII": "PII",
    "Logs": "Logs",
    "Auditoria": "Auditoria",
    "Compliance": "Compliance",
    "SOC 2": "SOC 2",
    "HIPAA": "HIPAA",
    "GDPR": "GDPR",
    "EU AI Act": "EU AI Act",
    "ISO 42001": "ISO 42001",
    "FinOps": "FinOps",
    "Economia Unitaria": "Economia Unitária",
    "Atribuicao": "Atribuição",
    "Multi-Tenant": "Multi-Tenant",
    "Servico": "Serviço",
    "Self-Hosted": "Self-Hosted",
    "llama.cpp": "llama.cpp",
    "Ollama": "Ollama",
    "TGI": "TGI",
    "vLLM": "vLLM",
    "SGLang": "SGLang",

    # Phase 18 - Ethics
    "Sinal": "Sinal",
    "Lei": "Lei",
    "Goodhart": "Goodhart",
    "Familia": "Família",
    "Direct Preference Optimization": "Direct Preference Optimization",
    "Amplificacao": "Amplificação",
    "Engano Persistente": "Engano Persistente",
    "Fingimento": "Fingimento",
    "Controle": "Controle",
    "Supervisao": "Supervisão",
    "Escalavel": "Escalável",
    "Ataques": "Ataques",
    "Automatizados": "Automatizados",
    "Jailbreaking": "Jailbreaking",
    "Art": "Art",
    "Visuais": "Visuais",
    "Indirect Prompt Injection": "Indirect Prompt Injection",
    "Ferramentas": "Ferramentas",
    "Red-Team": "Red-Team",
    "Garak": "Garak",
    "Llama Guard": "Llama Guard",
    "PyRIT": "PyRIT",
    "WMDP": "WMDP",
    "Dual-Use": "Dual-Use",
    "Frameworks": "Frameworks",
    "Fronteira": "Fronteira",
    "RSP": "RSP",
    "PF": "PF",
    "FSF": "FSF",
    "Bem-Estar": "Bem-Estar",
    "Modelos": "Modelos",
    "Dano": "Dano",
    "Representacional": "Representacional",
    "Criterios": "Critérios",
    "Justica": "Justiça",
    "Grupo": "Grupo",
    "Individual": "Individual",
    "Contrafactual": "Contrafactual",
    "Privacidade": "Privacidade",
    "Diferencial": "Diferencial",
    "SynthID": "SynthID",
    "Stable Signature": "Stable Signature",
    "C2PA": "C2PA",
    "Regulatorios": "Regulatórios",
    "Coreia": "Coreia",
    "EchoLeak": "EchoLeak",
    "CVEs": "CVEs",
    "Cards": "Cards",
    "Proveniencia": "Proveniência",
    "Dados": "Dados",
    "Treinamento": "Treinamento",
    "Governanca": "Governança",
    "Ecossistema": "Ecossistema",
    "Pesquisa": "Pesquisa",
    "MATS": "MATS",
    "Redwood": "Redwood",
    "Apollo": "Apollo",
    "METR": "METR",
    "Moderacao": "Moderação",
    "OpenAI": "OpenAI",
    "Perspective": "Perspective",
    "Risco": "Risco",
    "Ciber": "Ciber",
    "Bio": "Bio",
    "Quimico": "Químico",
    "Nuclear": "Nuclear",

    # General / catch-all patterns
    "Logica": "Lógica",
    "Tecnicas": "Técnicas",
    "Tecnica": "Técnica",
    "Assincrona": "Assíncrona",
    "Duravel": "Durável",
    "Executaveis": "Executáveis",
    "Nivel": "Nível",
    "Orcamento": "Orçamento",
    "Instancia": "Instância",
    "Audio": "Áudio",
    "Distancia": "Distância",
    "Subversao": "Subversão",
    "Hierarquico": "Hierárquico",
    "Hierarquica": "Hierárquica",
    "Codigo": "Código",
    "Hibrida": "Híbrida",
    "Dinamica": "Dinâmica",
    "Musica": "Música",
    "Hiperparametros": "Hiperparâmetros",
    "Paralelo": "Paralelo",
    "Automatico": "Automático",
    "Publico": "Público",
    "Numerico": "Numérico",
}


def fix_pt_text(text):
    """Apply all known fixes to a Portuguese string."""
    # Sort by length (descending) so longer matches take priority
    for wrong, correct in sorted(FIXES.items(), key=lambda x: -len(x[0])):
        if wrong != correct:
            text = text.replace(wrong, correct)
    return text


def process_file(path):
    with open(path, 'r', encoding='utf-8') as f:
        lines = f.readlines()

    modified_lines = []
    total_fixes = 0
    line_fixes = []

    for lineno, line in enumerate(lines, 1):
        # Only modify lines that contain pt-br translation values
        # A translation line looks like: "    'Key': 'Value',"
        # We only want to fix the Value part (after the colon)
        if "': '" in line and line.strip().startswith("'"):
            # Split on ": '" to separate key from value
            parts = line.split("': '", 1)
            if len(parts) == 2:
                key_part = parts[0] + "': '"
                value_part = parts[1]
                # Find the closing quote
                if value_part.endswith("',\n"):
                    value = value_part[:-3]
                    suffix = "',\n"
                elif value_part.endswith("'\n"):
                    value = value_part[:-2]
                    suffix = "'\n"
                elif value_part.endswith("'"):
                    value = value_part[:-1]
                    suffix = "'"
                else:
                    modified_lines.append(line)
                    continue

                fixed_value = fix_pt_text(value)
                if fixed_value != value:
                    total_fixes += 1
                    line_fixes.append((lineno, value, fixed_value))
                    modified_lines.append(f"{key_part}{fixed_value}{suffix}")
                else:
                    modified_lines.append(line)
            else:
                modified_lines.append(line)
        else:
            modified_lines.append(line)

    # Write back
    with open(path, 'w', encoding='utf-8') as f:
        f.writelines(modified_lines)

    print(f"Fixed {total_fixes} translation values.")
    if line_fixes:
        print("\nChanges made:")
        for ln, old, new in line_fixes:
            print(f"  L{ln}: '{old}' -> '{new}'")


if __name__ == '__main__':
    process_file('site/content-translations.js')
