#!/usr/bin/env python3
"""Restore missing Portuguese accents in Phase 10 files."""
import glob

# Mapping WITHOUT the problematic ' e ' -> ' é ' that over-matches
# Only words we're CERTAIN should have accents
ACCENT_MAP = {
    # Common stripped words
    "nao": "não",
    "Nao": "Não",
    "voce": "você",
    "Voce": "Você",
    "Pre-": "Pré-",
    "otimizacao": "otimização",
    "Otimizacao": "Otimização",
    "instrucao": "instrução",
    "Instrucao": "Instrução",
    "instrucoes": "instruções",
    "Instrucoes": "Instruções",
    "preferencia": "preferência",
    "Preferencia": "Preferência",
    "preferencias": "preferências",
    "Preferencias": "Preferências",
    "inferencia": "inferência",
    "Inferencia": "Inferência",
    "inferencias": "inferências",
    "Inferencias": "Inferências",
    "probabilidade": "probabilidade",
    "diferenca": "diferença",
    "Diferenca": "Diferença",
    "diferencas": "diferenças",
    "Diferencas": "Diferenças",
    "analise": "análise",
    "Analise": "Análise",
    "epoca": "época",
    "Epoca": "Época",
    "logica": "lógica",
    "Logica": "Lógica",
    "numerico": "numérico",
    "Numerico": "Numérico",
    "numerica": "numérica",
    "Numerica": "Numérica",
    "metricas": "métricas",
    "Metricas": "Métricas",
    "Metodos": "Métodos",
    "metodos": "métodos",
    "Metodo": "Método",
    "tecnica": "técnica",
    "Tecnica": "Técnica",
    "tecnicas": "técnicas",
    "Tecnicas": "Técnicas",
    "automatico": "automático",
    "Automatico": "Automático",
    "automatica": "automática",
    "Automatica": "Automática",
    "otimo": "ótimo",
    "Otimo": "Ótimo",
    "area": "área",
    "Area": "Área",
    "ultima": "última",
    "Ultima": "Última",
    "ultimo": "último",
    "Ultimo": "Último",
    "maximo": "máximo",
    "Maximo": "Máximo",
    "minimo": "mínimo",
    "Minimo": "Mínimo",
    "minima": "mínima",
    "Minima": "Mínima",
    "dinamica": "dinâmica",
    "Dinamica": "Dinâmica",
    "dinamico": "dinâmico",
    "Dinamico": "Dinâmico",
    "sintese": "síntese",
    "Sintese": "Síntese",
    "generica": "genérica",
    "generico": "genérico",
    "estatico": "estático",
    "estatica": "estática",
    "razao": "razão",
    "Razao": "Razão",
    "razoes": "razões",
    "Razoes": "Razões",
    "ambito": "âmbito",
    "Ambito": "Âmbito",
    "indice": "índice",
    "Indice": "Índice",
    "indices": "índices",
    "Indices": "Índices",
    "util": "útil",
    "Util": "Útil",
    
    # Word-ending accent patterns (most reliable)
    "acao": "ação",
    "Acao": "Ação",
    "coes": "ções",
    "oes": "ões",
    "ao\n": "ão\n",
    "ao ": "ão ",
    "ao.": "ão.",
    "ao,": "ão,",
    "ao?": "ão?",
    "cao ": "ção ",
    "cao.": "ção.",
    "cao\n": "ção\n",
    "cao,": "ção,",
    "cao?": "ção?",
    "cao!": "ção!",
}

# Full-word mappings for specific words
WORD_MAP = {
    "geracao": "geração",
    "Geracao": "Geração",
    "traducao": "tradução",
    "Traducao": "Tradução",
    "atencao": "atenção",
    "Atencao": "Atenção",
    "decisao": "decisão",
    "Decisao": "Decisão",
    "operacao": "operação",
    "Operacao": "Operação",
    "operacoes": "operações",
    "Operacoes": "Operações",
    "selecao": "seleção",
    "Selecao": "Seleção",
    "avancado": "avançado",
    "Avancado": "Avançado",
    "reducao": "redução",
    "Reducao": "Redução",
    "producao": "produção",
    "Producao": "Produção",
    "seguranca": "segurança",
    "Seguranca": "Segurança",
    "comunicacao": "comunicação",
    "Comunicacao": "Comunicação",
    "implementacao": "implementação",
    "Implementacao": "Implementação",
    "aplicacao": "aplicação",
    "Aplicacao": "Aplicação",
    "aplicacoes": "aplicações",
    "Aplicacoes": "Aplicações",
    "organizacao": "organização",
    "Organizacao": "Organização",
    "utilizacao": "utilização",
    "Utilizacao": "Utilização",
    "transformacao": "transformação",
    "transformacoes": "transformações",
    "combinacao": "combinação",
    "Combinacao": "Combinação",
    "explicacao": "explicação",
    "Explicacao": "Explicação",
    "conversao": "conversão",
    "Conversao": "Conversão",
    "simulacao": "simulação",
    "Simulacao": "Simulação",
    "variacao": "variação",
    "Variacao": "Variação",
    "posicao": "posição",
    "Posicao": "Posição",
    "posicoes": "posições",
    "Posicoes": "Posições",
    "limitacao": "limitação",
    "Limitacao": "Limitação",
    "computacao": "computação",
    "Computacao": "Computação",
    "tokenizacao": "tokenização",
    "Tokenizacao": "Tokenização",
    "parametro": "parâmetro",
    "Parametro": "Parâmetro",
    "parametros": "parâmetros",
    "Parametros": "Parâmetros",
    "configuracao": "configuração",
    "Configuracao": "Configuração",
    "avaliacao": "avaliação",
    "Avaliacao": "Avaliação",
    "avaliacoes": "avaliações",
    "Avaliacoes": "Avaliações",
    "informacao": "informação",
    "Informacao": "Informação",
    "informacoes": "informações",
    "Informacoes": "Informações",
    "representacao": "representação",
    "Representacao": "Representação",
    "classificacao": "classificação",
    "Classificacao": "Classificação",
    "demonstracao": "demonstração",
    "Demonstracao": "Demonstração",
    "observacao": "observação",
    "Observacao": "Observação",
    "observacoes": "observações",
    "Observacoes": "Observações",
    "visualizacao": "visualização",
    "Visualizacao": "Visualização",
    "otimizador": "otimizador",
    "restricao": "restrição",
    "Restricao": "Restrição",
    "deteccao": "detecção",
    "Deteccao": "Detecção",
    "segmentacao": "segmentação",
    "Segmentacao": "Segmentação",
    "articulacao": "articulação",
    "Articulacao": "Articulação",
    "estimacao": "estimação",
    "Estimacao": "Estimação",
    "estimativa": "estimativa",
    "compreensao": "compreensão",
    "Compreensao": "Compreensão",
    "correlacao": "correlação",
    "Correlacao": "Correlação",
    "graduacao": "graduação",
    "aprimoramento": "aprimoramento",
    "capacidade": "capacidade",
    "estrategia": "estratégia",
    "Estrategia": "Estratégia",
    "experiencia": "experiência",
    "Experiencia": "Experiência",
    "audiencia": "audiência",
    "Audiencia": "Audiência",
    "absorcao": "absorção",
    "Absorcao": "Absorção",
    "mencao": "menção",
    "Mencao": "Menção",
    "atualizacao": "atualização",
    "Atualizacao": "Atualização",
    "sincronizacao": "sincronização",
    "Sincronizacao": "Sincronização",
    "particularmente": "particularmente",
    "proporcional": "proporcional",
    "automaticamente": "automaticamente",
    "visualmente": "visualmente",
    "conhecimento": "conhecimento",
    "proximo": "próximo",
    "Proximo": "Próximo",
    "proximo": "próximo",
    "inicio": "início",
    "Inicio": "Início",
    "serie": "série",
    "Serie": "Série",
    "tres": "três",
    "Tres": "Três",
    "ate": "até",
    "Ate": "Até",
    "alem": "além",
    "Alem": "Além",
    "atraves": "através",
    "Atraves": "Através",
    "apos": "após",
    "Apos": "Após",
    "tambem": "também",
    "Tambem": "Também",
}

ACCENT_MAP.update(WORD_MAP)

pt10_files = glob.glob("phases/10-llms-from-scratch/*/docs/pt-br.md")
count = 0
for fpath in sorted(pt10_files):
    with open(fpath) as f:
        content = f.read()
    orig = content
    for wrong, correct in sorted(ACCENT_MAP.items(), key=lambda x: -len(x[0])):
        content = content.replace(wrong, correct)
    if content != orig:
        with open(fpath, "w") as f:
            f.write(content)
        count += 1

print(f"Restored accents in {count} files")
